version: "3.4"

services:
  frontend:
    image: frontend
    build: ./frontend
    environment:
      NODE_ENV: development
      VITE_MAP_API_KEY: AIzaSyAQxOROxTZ1KpfadrenQPNO9I-gb3vGjvE
    ports:
      - 5000:5000
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules

  backend:
    image: backend
    build: ./backend
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    command: ["nodemon", "--inspect", "index.js"]
